changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feat
        - feature
    - title: Fixes and minor updates
      labels:
        - fix
        - bugfix
        - refactor
        - hotfix
    - title: Other Changes
      labels:
        - "*"